# Generated by Django 4.1.7 on 2023-03-11 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_users_comment_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_post',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='base.post'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bca_class',
            field=models.CharField(choices=[('1st Sem', '1st Sem'), ('2nd Sem', '2nd Sem'), ('3rd Sem', '3rd Sem'), ('4th Sem', '4th Sem'), ('5th Sem', '5th Sem'), ('6th Sem', '6th Sem')], default=('1st Sem', '1st Sem'), max_length=50, null=True),
        ),
    ]
