# Generated by Django 4.1.7 on 2023-03-11 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_question_answer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='title',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='body',
        ),
    ]
