# Generated by Django 4.1.7 on 2023-03-11 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
