# Generated by Django 4.1.7 on 2023-03-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_notes_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='bca_class',
            field=models.CharField(choices=[('1st Sem', '1st Sem'), ('2nd Sem', '2nd Sem'), ('3rd Sem', '3rd Sem'), ('4th Sem', '4th Sem'), ('5th Sem', '5th Sem'), ('6th Sem', '6th Sem')], default='1st Sem', max_length=50),
        ),
    ]
