# Generated by Django 4.1.7 on 2023-03-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_note_bca_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='topic',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
