# Generated by Django 4.1.7 on 2023-03-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_room_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='body',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='room',
            name='image',
        ),
        migrations.RemoveField(
            model_name='room',
            name='user',
        ),
    ]
