# Generated by Django 4.1.7 on 2023-03-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_choice_votes'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='voted',
            field=models.BooleanField(default=False),
        ),
    ]
