from django.urls import path
from .views import *

urlpatterns = [
    path('' , home, name = 'home'),
    path('add-post', add_post, name = 'add-post'),
    path('like-post/', like_post , name = 'like-post'),
    path('post-comments/<int:id>' , post_comments , name = 'post-comments'),
    path('add-post-comment/<int:id>', add_post_comment ,name = 'add-post-comment'),
    path('login' , login_view , name = 'login'),
    path('logout' , logout_view , name = 'logout'),
    path('register-student' , register_student, name = 'register-student'),
    path('register-teacher', register_teacher, name = 'register-teacher'),
    path('delete-post/<int:id>', delete_post, name = 'delete-post'),
    path('delete-comment/<int:id>', delete_comment, name = 'delete-comment'),
    path('show-profile/<int:id>', show_profile, name = 'show-profile'),
    path('edit-profile' , edit_profile , name = 'edit-profile'),
    path('ask-question', ask_question, name = 'ask-question'),
    path('questions', questions, name = 'questions'),
    path('answers/<int:id>', answers, name = 'answers'),
    path('answer/<int:id>' ,answer, name = 'answer'),
    path('notes', notes , name = 'notes'),
    path('add-note', add_note, name = 'add-note'),
    path('follow/<int:id>', follow, name = 'follow'),
    path('followers/<int:id>', followers , name= 'followers'),
    path('following/<int:id>', following, name = 'following'),
    path('user-search', user_search, name = 'user-search' ),
    path('rooms', rooms, name = 'rooms'),
    path('add-room', add_room, name = 'add-room'),
    path('room/<int:id>', room, name= 'room'),
    path('resumes', resumes, name = 'resumes'),
    path('resume/<int:id>', resume, name = 'resume'),
    path('add-resume', add_resume, name = 'add-resume'),
    path('get-messages/<int:id>', get_messages, name = 'get-messages' ),
    path('polls', polls, name = 'polls'),
    path('add-poll', add_poll, name = 'add-poll'),
    path('poll/<int:id>', poll, name = 'poll'),
    path('poll-vote/' , poll_vote, name = 'poll-vote'),
]
